cycles_delay: 60

elastic:
  host: elastic
  port: 9200

postgress_dsn:
  host: db
  port: 5432
  dbname: movies_database
  user: ЗНАЧЕНИЕ БУДЕТ ПЕРЕЗАПИСАНО ПЕРЕМЕННОЙ ОКРУЖЕНИЯ - POSTGRES_USER
  password: ЗНАЧЕНИЕ БУДЕТ ПЕРЕЗАПИСАНО ПЕРЕМЕННОЙ ОКРУЖЕНИЯ - POSTGRES_PASSWORD
  options: '-c search_path=content'

etl_tasks:
  - chunk_size: 100
    data_class: !!python/name:etl_tasks.film_work.data_structures.FilmWork
    pg:
      table: film_work
      queries:
        extract: 'etl_tasks/film_work/extract.sql'
        enrich: 'etl_tasks/film_work/enrich.sql'
    es:
      index: movies
      mapping: 'etl_tasks/film_work/index_mapping.json'
      settings: 'etl_tasks/film_work/index_settings.json'

  - chunk_size: 100
    data_class: !!python/name:etl_tasks.genre.data_structures.Genre
    pg:
      table: genre
      queries:
        extract: 'etl_tasks/genre/extract.sql'
        enrich: 'etl_tasks/genre/enrich.sql'
    es:
      index: genres
      mapping: 'etl_tasks/genre/index_mapping.json'
      settings: 'etl_tasks/genre/index_settings.json'

  - chunk_size: 100
    data_class: !!python/name:etl_tasks.person.data_structures.Person
    pg:
      table: person
      queries:
        extract: 'etl_tasks/person/extract.sql'
        enrich: 'etl_tasks/person/enrich.sql'
    es:
      index: persons
      mapping: 'etl_tasks/person/index_mapping.json'
      settings: 'etl_tasks/person/index_settings.json'
