version: "3"
services:
  nginx:
    image: nginx:1.21.4
    container_name: nginx
    restart: on-failure
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/conf.d:/etc/nginx/conf.d
      - ./movies_admin/static/:/static
    ports:
      - "80:80"

  elastic:
    image: elasticsearch:7.16.3
    container_name: elastic
    restart: always
    environment:
      - discovery.type=single-node
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    volumes:
      - es:/usr/share/elasticsearch/data
    expose:
      - 9200

  mongo:
    image: mongo:5.0.5
    container_name: mongo_storage
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD}
    volumes:
      - ./volumes/mongo:/data/db
    expose:
      - 27017

  redis:
    image: redis:6.2.6-bullseye
    container_name: redis
    restart: always
    command: redis-server
    expose:
      - 6379

  etl:
    build: ./etl/
    container_name: etl
    restart: always
    env_file:
      - ".env"
    volumes:
      - ./etl/indexes/:/usr/src/etl/indexes
      - ./etl/log/:/usr/src/etl/log
    depends_on:
      - redis
      - mongo
      - elastic
    links:
      - redis

  api:
    build: ./src/
    container_name: api
    restart: always
    environment:
      - PROJECT_NAME=${PROJECT_NAME}
      - ELASTIC_HOST=${ELASTIC_HOST}
      - ELASTIC_PORT=${ELASTIC_PORT}
      - REDIS_HOST=${REDIS_HOST}
      - REDIS_PORT=${REDIS_PORT}
    ports:
      - "8000:8000"
    depends_on:
      - redis
      - elastic



volumes:
    es:
      external: true
