<<<<<<< HEAD
version: "3"
services:
  fastapi:
    container_name: fastapi
    build:
      context: ./src
      dockerfile: fastapi.dockerfile
    env_file:
      - .env
    #volumes:
    #  - ./src:/app
    depends_on:
      - redis
      - elastic
      - postgres
    ports:
      - "8000:8000"

  elastic:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.7.0
    container_name: elastic
    environment:
      - discovery.type=single-node
    ports:
      - "9200:9200"

  postgres:
    image: postgres:13
    container_name: postgres
    environment:
      - POSTGRES_PASSWORD=mysecretpassword
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:6.0.9
    container_name: redis
    ports:
      - 6379:6379
    depends_on:
      - elastic

volumes:
    postgres_data:
      external: true
=======
services:
  postgres:
    image: postgres:14.1-alpine3.15
    container_name: postgres
    ports:
      - ${POSTGRES_PORT}:5432
    restart: always
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    volumes:
      - ./volumes/db:/var/lib/postgresql/data

  admin_panel:
    build: ./movies_admin/
    container_name: admin_panel
    restart: always
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_HOST=postgres
      - POSTGRES_PORT=${POSTGRES_PORT}
      - SECRET_KEY=${SECRET_KEY}
    volumes:
      - ./movies_admin/film_works/:/usr/src/movies_admin/film_works
    depends_on:
      - postgres
    command: gunicorn --bind 0.0.0.0:8000 config.wsgi --reload

  nginx:
    image: nginx:1.21.4
    container_name: nginx
    restart: on-failure
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/conf.d:/etc/nginx/conf.d
      - ./movies_admin/static/:/static
    ports:
      - 80:80
    depends_on:
      - admin_panel
      - postgres

  elastic:
    image: elasticsearch:7.16.3
    container_name: elastic
    restart: always
    environment:
      - discovery.type=single-node
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    volumes:
      - es:/usr/share/elasticsearch/data
    ports:
      - ${ELASTIC_PORT}:9200

  mongo:
    image: mongo:5.0.5
    container_name: mongo_storage
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD}
    volumes:
      - ./volumes/mongo:/data/db
    ports:
      - ${MONGO_PORT}:27017

  redis:
    image: redis:6.2.6-bullseye
    container_name: redis
    restart: always
    command: redis-server
    ports:
      - ${REDIS_PORT}:6379

  etl:
    build: ./etl/
    container_name: etl
    restart: always
    env_file:
      - ".env"
    volumes:
      - ./etl/indexes/:/usr/src/etl/indexes
      - ./etl/log/:/usr/src/etl/log
    depends_on:
      - redis
      - mongo
      - elastic
      - postgres
    links:
      - redis

volumes:
  es:
    driver: local
>>>>>>> feature/dev
